import { Agent } from "../types/agent";

export const sampleAgents: Agent[] = [
  {
    id: "agent-001",
    name: "Adaeze Okonkwo",
    title: "Senior Property Advisor",
    company: "Mighty Estates",
    location: "Lagos, Nigeria",
    phone: "+234 802 123 4567",
    email: "adaeze@mightyestates.com",
    rating: 4.9,
    listingsCount: 24,
    verified: true,
    specialties: ["Luxury Homes", "Lekki", "Victoria Island", "Banana Island"],
    photo: "/images/agents/adaeze.webp",
    bio: "Specializing in high-end residential properties across Lagos' premium locations. Over 10 years of experience helping clients find their dream homes.",
  },
  {
    id: "agent-002",
    name: "Chukwuemeka Nnamdi",
    title: "Commercial Property Specialist",
    company: "Mighty Estates",
    location: "Abuja, Nigeria",
    phone: "+234 803 456 7890",
    email: "emeka@mightyestates.com",
    rating: 4.8,
    listingsCount: 15,
    verified: true,
    specialties: [
      "Commercial Buildings",
      "Office Space",
      "Investment Properties",
      "Maitama",
    ],
    photo: "/images/agents/emeka.webp",
    bio: "Expert in commercial real estate across the FCT. Helps businesses and investors find the perfect location for their needs.",
  },
  {
    id: "agent-003",
    name: "Folake Adebayo",
    title: "Residential Listings Lead",
    company: "Mighty Estates",
    location: "Lagos, Nigeria",
    phone: "+234 806 789 0123",
    email: "folake@mightyestates.com",
    rating: 4.8,
    listingsCount: 32,
    verified: true,
    specialties: [
      "Apartments",
      "Ikeja",
      "Ikoyi",
      "Rentals",
      "New Developments",
    ],
    photo: "/images/agents/folake.webp",
    bio: "Deep knowledge of Lagos island and mainland markets. Dedicated to helping buyers and renters find the best properties.",
  },
  {
    id: "agent-004",
    name: "Oluwaseun Oladipo",
    title: "Land & Development Consultant",
    company: "Mighty Estates",
    location: "Ogun, Nigeria",
    phone: "+234 807 234 5678",
    email: "seun@mightyestates.com",
    rating: 4.7,
    listingsCount: 18,
    verified: true,
    specialties: ["Land", "Vacation Homes", "Ogun State", "Sangotedo"],
    photo: "/images/agents/seun.webp",
    bio: "Focuses on land acquisitions and development projects in Ogun State and axis areas. Extensive network of developers and investors.",
  },
  {
    id: "agent-005",
    name: "Emeka Okafor",
    title: "Port Harcourt Regional Manager",
    company: "Mighty Estates",
    location: "Port Harcourt, Nigeria",
    phone: "+234 805 678 9012",
    email: "emeka@mightyestates.com",
    rating: 4.9,
    listingsCount: 12,
    verified: true,
    specialties: [
      "Oil & Gas Housing",
      "Commercial",
      "Port Harcourt",
      "Warehouses",
    ],
    photo: "/images/agents/emeka-okafor.webp",
    bio: "Specialized in serving the oil and gas industry with premium housing solutions in Port Harcourt and surrounding areas.",
  },
];
