import { Listing } from "../types/listing";

export const sampleListings: Listing[] = [
  {
    id: "house-001",
    title: "Luxury Detached House in Lekki",
    price: 85000000,
    priceCurrency: "₦",
    type: "house",
    bedrooms: 5,
    bathrooms: 4,
    sizeSqm: 450,
    status: "active",
    featured: true,
    mainImage: "/images/properties/house-1.webp",
    images: ["/images/properties/house-1.webp"],
    address: { line1: "Orchid Road", city: "Lekki", region: "Lagos" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "house-002",
    title: "4 Bedroom Semi-Detached in Gwarinpa",
    price: 45000000,
    priceCurrency: "₦",
    type: "house",
    bedrooms: 4,
    bathrooms: 3,
    sizeSqm: 280,
    status: "active",
    featured: false,
    mainImage: "/images/properties/house-2.webp",
    images: ["/images/properties/house-2.webp"],
    address: { line1: "5th Avenue", city: "Gwarinpa", region: "Abuja" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "apt-001",
    title: "Modern 2 Bedroom Flat in Victoria Island",
    price: 35000000,
    priceCurrency: "₦",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 120,
    status: "active",
    featured: true,
    mainImage: "/images/properties/apt-1.webp",
    images: ["/images/properties/apt-1.webp"],
    address: {
      line1: "Ahmadu Bello Way",
      city: "Victoria Island",
      region: "Lagos",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "apt-002",
    title: "Serviced Apartment in Maitama",
    price: 28000000,
    priceCurrency: "₦",
    type: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    sizeSqm: 95,
    status: "active",
    featured: false,
    mainImage: "/images/properties/apt-2.webp",
    images: ["/images/properties/apt-2.webp"],
    address: { line1: "Yunis Street", city: "Maitama", region: "Abuja" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "apt-003",
    title: "3 Bedroom Flat in Ikeja GRA",
    price: 55000000,
    priceCurrency: "₦",
    type: "apartment",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 180,
    status: "active",
    mainImage: "/images/properties/apt-3.webp",
    images: ["/images/properties/apt-3.webp"],
    address: { line1: "Oba Akinwunmi Way", city: "Ikeja", region: "Lagos" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "house-003",
    title: "5 Bedroom Duplex in Banana Island",
    price: 180000000,
    priceCurrency: "₦",
    type: "house",
    bedrooms: 5,
    bathrooms: 5,
    sizeSqm: 600,
    status: "active",
    featured: true,
    badges: ["featured"],
    mainImage: "/images/properties/house-3.webp",
    images: ["/images/properties/house-3.webp"],
    address: {
      line1: "Princess Sidi Street",
      city: "Banana Island",
      region: "Lagos",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "comm-001",
    title: "Commercial Office Space in Marina",
    price: 120000000,
    priceCurrency: "₦",
    type: "commercial",
    sizeSqm: 350,
    status: "active",
    featured: true,
    badges: ["new"],
    mainImage: "/images/properties/comm-1.webp",
    images: ["/images/properties/comm-1.webp"],
    address: {
      line1: "Marina Boulevard",
      city: "Lagos Island",
      region: "Lagos",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "comm-002",
    title: "Warehouse in Port Harcourt",
    price: 75000000,
    priceCurrency: "₦",
    type: "commercial",
    sizeSqm: 500,
    status: "active",
    mainImage: "/images/properties/comm-2.webp",
    images: ["/images/properties/comm-2.webp"],
    address: {
      line1: "Trans Amadi Road",
      city: "Port Harcourt",
      region: "Rivers",
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-001",
    title: "Plot of Land in Sangotedo",
    price: 25000000,
    priceCurrency: "₦",
    type: "land",
    sizeSqm: 600,
    status: "active",
    featured: false,
    badges: ["new"],
    mainImage: "/images/properties/land-1.webp",
    images: ["/images/properties/land-1.webp"],
    address: { line1: "Lagos Road", city: "Sangotedo", region: "Lagos" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-002",
    title: "Land for Sale in Karaye, Kano",
    price: 15000000,
    priceCurrency: "₦",
    type: "land",
    sizeSqm: 1000,
    status: "active",
    mainImage: "/images/properties/land-2.webp",
    images: ["/images/properties/land-2.webp"],
    address: { line1: "Kano Road", city: "Karaye", region: "Kano" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "house-004",
    title: "3 Bedroom Bungalow in Surulere",
    price: 32000000,
    priceCurrency: "₦",
    type: "house",
    bedrooms: 3,
    bathrooms: 2,
    sizeSqm: 200,
    status: "active",
    mainImage: "/images/properties/house-4.webp",
    images: ["/images/properties/house-4.webp"],
    address: { line1: "Adeleke Street", city: "Surulere", region: "Lagos" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "house-005",
    title: "Detached House in Asokoro, Abuja",
    price: 95000000,
    priceCurrency: "₦",
    type: "house",
    bedrooms: 6,
    bathrooms: 5,
    sizeSqm: 520,
    status: "active",
    featured: true,
    mainImage: "/images/properties/house-5.webp",
    images: ["/images/properties/house-5.webp"],
    address: { line1: "Rivers Street", city: "Asokoro", region: "Abuja" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "apt-004",
    title: "Penthouse in Ikoyi",
    price: 150000000,
    priceCurrency: "₦",
    type: "apartment",
    bedrooms: 4,
    bathrooms: 4,
    sizeSqm: 320,
    status: "active",
    featured: true,
    badges: ["luxury"],
    mainImage: "/images/properties/apt-4.webp",
    images: ["/images/properties/apt-4.webp"],
    address: { line1: "Awolowo Road", city: "Ikoyi", region: "Lagos" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "land-003",
    title: "Land in Enugu - New Haven",
    price: 18000000,
    priceCurrency: "₦",
    type: "land",
    sizeSqm: 450,
    status: "active",
    mainImage: "/images/properties/land-3.webp",
    images: ["/images/properties/land-3.webp"],
    address: { line1: "New Haven Road", city: "Enugu", region: "Enugu" },
    createdAt: new Date().toISOString(),
  },
  {
    id: "comm-003",
    title: "Shop in Ibadan Mall",
    price: 45000000,
    priceCurrency: "₦",
    type: "commercial",
    sizeSqm: 45,
    status: "active",
    mainImage: "/images/properties/comm-3.webp",
    images: ["/images/properties/comm-3.webp"],
    address: { line1: "Ring Road", city: "Ibadan", region: "Oyo" },
    createdAt: new Date().toISOString(),
  },
];
